### ISSUE TITLE
TypeError: sequence item 1: expected str instance, NoneType found

### ISSUE THREAD

**Issue by Miserlou** [jrxFive/python-nomad#62]
```
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev Traceback (most recent call last):
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev   File "/home/user/data_refinery_foreman/foreman/main.py", line 304, in retry_hung_processor_jobs
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev     job_status = nomad_client.job.get_job(job.nomad_job_id)["Status"]
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/nomad/api/job.py", line 67, in get_job
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev     return self._get(id)
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/nomad/api/job.py", line 50, in _get
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev     url = self._requester._endpointBuilder(Job.ENDPOINT, *args)
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/nomad/api/base.py", line 25, in _endpointBuilder
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev     u = "/".join(args)
data-refinery-log-group-kurtwheeler-dev log-stream-foreman-kurtwheeler-dev TypeError: sequence item 1: expected str instance, NoneType found
```

Happens sometimes when Nomad is less-than-available..

**Comment by jrxFive** [comment]
Hey @Miserlou, in this case would be expecting a more clear cut exception to be raised? Seems there is good amount of pain so far to justify adding more detailed Exceptions in the library, ill certainly put is a priority if thats the case. Thanks for reporting the issue!
